[[scenario]]
name = "brotli-json-1kb-c32"
url = "http://{{ server }}/json/1kb"
connections = 32
max_throughput = true
duration = {{ duration }}
warmup = {{ warmup }}

[scenario.headers]
Accept-Encoding = "br"
