[[scenario]]
name = "brotli-json-1kb-c128"
url = "http://{{ server }}/json/1kb"
connections = 128
max_throughput = true
duration = {{ duration }}
warmup = {{ warmup }}

[scenario.headers]
Accept-Encoding = "br"
