name = "http-basic"
description = "Basic HTTP benchmark cases using Spinr and wrk3"

[[case]]
id = "text-c128"
generator = "spinr"
template = "../spinr/text-c128.toml"
concurrency = 128

[[case]]
id = "text-wrk3-c128"
generator = "wrk3"
template = "../wrk3/text-c128.wrk3.toml"
concurrency = 128
rate = 50000

[case.context]
path = "/text"
