- name: Benchmark instances
  hosts: all
  vars:
    ecr_registry: "529001354082.dkr.ecr.eu-west-1.amazonaws.com"
    aws_region: "eu-west-1"
    harrow_version: "{{ harrow_version }}"
    spinr_version: "{{ spinr_version }}"
    wrk3_version: "{{ wrk3_version | default('0.2.0') }}"
  roles:
    - role: os
    - role: packages
    - role: docker
    - role: ecr-login
    - role: pull-images
    - role: vector
