- name: Pull latest bench images from ECR
  hosts: all
  vars:
    ecr_registry: "529001354082.dkr.ecr.eu-west-1.amazonaws.com"
    aws_region: "eu-west-1"
    image_version: "{{ image_version }}"
  roles:
    - role: ecr-login
    - role: pull-images
