# Server: pull perf server images
- name: Pull harrow-perf-server from ECR
  ansible.builtin.command:
    cmd: "docker pull {{ ecr_registry }}/harrow/harrow-perf-server:{{ harrow_version }}"
  changed_when: true
  when: inventory_hostname in groups['server']

- name: Tag harrow-perf-server for local use
  ansible.builtin.command:
    cmd: "docker tag {{ ecr_registry }}/harrow/harrow-perf-server:{{ harrow_version }} harrow-perf-server:arm64-{{ harrow_version }}"
  changed_when: true
  when: inventory_hostname in groups['server']

- name: Pull axum-perf-server from ECR
  ansible.builtin.command:
    cmd: "docker pull {{ ecr_registry }}/harrow/axum-perf-server:{{ harrow_version }}"
  changed_when: true
  when: inventory_hostname in groups['server']

- name: Tag axum-perf-server for local use
  ansible.builtin.command:
    cmd: "docker tag {{ ecr_registry }}/harrow/axum-perf-server:{{ harrow_version }} axum-perf-server:arm64-{{ harrow_version }}"
  changed_when: true
  when: inventory_hostname in groups['server']

# Server: pull monoio server image
- name: Pull harrow-server-monoio from ECR
  ansible.builtin.command:
    cmd: "docker pull {{ ecr_registry }}/harrow/harrow-server-monoio:{{ harrow_version }}"
  changed_when: true
  when: inventory_hostname in groups['server']

- name: Tag harrow-server-monoio for local use
  ansible.builtin.command:
    cmd: "docker tag {{ ecr_registry }}/harrow/harrow-server-monoio:{{ harrow_version }} harrow-server-monoio:arm64-{{ harrow_version }}"
  changed_when: true
  when: inventory_hostname in groups['server']

# Client: pull spinr load tester
- name: Pull spinr from ECR
  ansible.builtin.command:
    cmd: "docker pull {{ ecr_registry }}/harrow/spinr:{{ spinr_version }}"
  changed_when: true
  when: inventory_hostname in groups['client']

- name: Tag spinr for local use
  ansible.builtin.command:
    cmd: "docker tag {{ ecr_registry }}/harrow/spinr:{{ spinr_version }} spinr:arm64-{{ spinr_version }}"
  changed_when: true
  when: inventory_hostname in groups['client']

# Client: pull wrk3 load tester
- name: Pull wrk3 from ECR
  ansible.builtin.command:
    cmd: "docker pull {{ ecr_registry }}/harrow/load-generators:wrk3-v{{ wrk3_version }}"
  changed_when: true
  when: inventory_hostname in groups['client']

- name: Tag wrk3 for local use
  ansible.builtin.command:
    cmd: "docker tag {{ ecr_registry }}/harrow/load-generators:wrk3-v{{ wrk3_version }} wrk3:arm64-{{ wrk3_version }}"
  changed_when: true
  when: inventory_hostname in groups['client']
